version: "3"

services:
  mystore_frontend:
    build:
      context: ./mystore_frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
       - mystore_ms
    ports:
      - "8085:80"
  mystore_ms:
    build:
      context: ./bigstore_ms
      dockerfile: Dockerfile
    restart: always
    depends_on:
       - db
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DATABASE}
      URL : ${URL}
    ports:
      - "4000:4000"
    volumes:
      - ./bigstore_ms:/code
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/pg-data

  adminer:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: always
    ports:
      - "5050:80"

volumes:
  pg-data: